In [2]:
import Q_num as qn
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

### Create quaternion number/arrray

In [15]:
qn1 = qn.qn([0,1,2,3])
qn2 = qn.qn(np.array([[1,3,2,4],[0.13,4.15,22,5.123123]]))
qn3 = qn.qn(np.random.rand(30,20,10,4))
qn4 = qn.qn(np.random.rand(10,20,3)) #3D coordinate matrix will be converted to quaterniono matrix whose real part is 0

### Quaternion array attribute and indexing

In [38]:
display(qn1)
print(qn1.w)
print(qn1.x)
print(qn1.y)
print(qn1.z)

qn5 = qn4[:2,14:]
display(qn5)
print(qn5.w)
print(qn5.x)
print(qn5[0,:3]['x'])
print(qn5['x'][0,:3])
print(qn5[0,:3].x)

Quaternion Array (): 
'+0+1i+2j+3k'

0.0
1.0
2.0
3.0


Quaternion Array (2, 6): 
[['+0+0.926i+0.5387j+0.8014k' '+0+0.5251i+0.5006j+0.5319k'
  '+0+0.5134i+0.9545j+0.7415k' '+0+0.124i+0.6525j+0.07362k'
  '+0+0.8414i+0.9122j+0.8761k' '+0+0.8994i+0.6129j+0.6906k']
 ['+0+0.9119i+0.9875j+0.4615k' '+0+0.9995i+0.5248j+0.09973k'
  '+0+0.8965i+0.09812j+0.4974k' '+0+0.2132i+0.8037j+0.4552k'
  '+0+0.6802i+0.387j+0.2502k' '+0+0.9618i+0.0551j+0.9914k']]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0.92600399 0.52508071 0.51335586 0.12404193 0.84142188 0.89943653]
 [0.91192578 0.99950482 0.89654535 0.21316713 0.68020767 0.96175304]]
[0.92600399 0.52508071 0.51335586]
[0.92600399 0.52508071 0.51335586]
[0.92600399 0.52508071 0.51335586]


In [117]:
display(qn5.asMatrix())
display(qn5.asMatrix().shape)
display(qn5.compact().shape)

array([[[0.        , 0.92600399, 0.53871625, 0.80144767],
        [0.        , 0.52508071, 0.50064505, 0.53192078],
        [0.        , 0.51335586, 0.95448613, 0.74154012],
        [0.        , 0.12404193, 0.65248967, 0.07361991],
        [0.        , 0.84142188, 0.91221122, 0.87608863],
        [0.        , 0.89943653, 0.61294624, 0.69057215]],

       [[0.        , 0.91192578, 0.98745544, 0.46145466],
        [0.        , 0.99950482, 0.5247622 , 0.09973027],
        [0.        , 0.89654535, 0.09811743, 0.49740932],
        [0.        , 0.21316713, 0.80365044, 0.45522333],
        [0.        , 0.68020767, 0.38695654, 0.25020782],
        [0.        , 0.96175304, 0.05510389, 0.99137815]]])

(2, 6, 4)

(12, 4)

In [73]:
# Known bug 1: when all indexes are intergers but not slice (3 vs 0:5), it will return numpy.void object but not qn object
qn4[0,3].w # bug
# Known bug 2: the subset quaternion array can't be printed but can be displayed,some bugs related with the custom __getitem__ and __repr__ functions
print(qn5['w']) # this is fine
print(qn5[:2,:]['w']) # this is also fine
print(qn5[:2,:]) # bug
print(qn5) #bug
display(qn5[:1,:3])

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### basic calculation

In [109]:
display(qn2 + qn2)
display(qn2 + qn1) # boardcasting
display(qn1 - qn2)
display(qn1 * qn2) # Check if the calculation is correct
display(qn2 * qn1) # also this
display(qn2 * 12)
display(qn2 / qn1)
display(qn1 / qn2)
display(qn1 / 8)
display(qn1.inv())
display(1 / qn1)
display((1 / qn1).x)
display(qn.exp(qn2))
display(qn.exp(qn1)) # known bug: if the quaternion number contains a 0, will yield out nan; will fix it soon
display(qn1.sum()) # not recommended, sometimes will give typeerror, use Q_num.sum instead
display(qn.sum(qn1))
display(qn.mean(qn1))

Quaternion Array (2,): 
['+2+6i+4j+8k' '+0.26+8.3i+44j+10.25k']

Quaternion Array (2,): 
['+3+10i+8j+15k' '+0.39+13.45i+68j+18.37k']

Quaternion Array (2,): 
['+1+4i+4j+7k' '+0.13+5.15i+24j+8.123k']

Quaternion Array (2,): 
['-75+15i+15j+15k' '-1118-53.47i+19.03j+16.75k']

Quaternion Array (2,): 
['-75+11i+5j+23k' '-1118+58.04i+4.373j-10.65k']

Quaternion Array (2,): 
['+12+36i+24j+48k' '+1.56+49.8i+264j+61.48k']

Quaternion Array (2,): 
['+0.3762+0.004762i+0.01429j-0.03333k'
 '+0.4703-0.0235i+0.002972j+0.005597k']

Quaternion Array (2,): 
['+2.633-0.03333i-0.1j+0.2333k' '+2.12+0.1059i-0.0134j-0.02523k']

Quaternion Array (2,): 
['+0.25+0.875i+0.75j+1.375k' '+0.0325+1.163i+5.75j+1.656k']

Quaternion Array (2,): 
['+0.009524-0.03333i-0.02857j-0.05238k'
 '+0.0001093-0.003911i-0.01934j-0.00557k']

Quaternion Array (2,): 
['+0.009524-0.03333i-0.02857j-0.05238k'
 '+0.0001093-0.003911i-0.01934j-0.00557k']

array([-0.03333333, -0.00391082])

Quaternion Array (2,): 
['+1.694-1.184i-0.7896j-1.579k' '-0.6386-0.1704i-0.9033j-0.2103k']

Quaternion Array (2,): 
['-1.58+3.52i+3.017j+5.532k' '+0.09016-0.2467i-1.22j-0.3514k']

Quaternion Array (): 
'+2.26+16.3i+52j+24.25k'

Quaternion Array (): 
'+2.26+16.3i+52j+24.25k'

Quaternion Array (): 
'+1.13+8.15i+26j+12.12k'

In [121]:
display(qn2.imag())
display(qn2.real())
display(qn2.imagpart())
display(qn2.realpart())
display(qn2.norm())
display(qn2/qn2.norm())
display(qn2.normalize())
display(qn5.qT()) # quaternion matrix transpose 

Quaternion Array (2,): 
['+0+3i+2j+4k' '+0+4.15i+22j+5.123k']

Quaternion Array (2,): 
['+1+0i+0j+0k' '+0.13+0i+0j+0k']

array([[ 3.      ,  2.      ,  4.      ],
       [ 4.15    , 22.      ,  5.123123]])

array([1.  , 0.13])

array([ 5.47722558, 22.96705879])

Quaternion Array (2,): 
['+0.1826+0.5477i+0.3651j+0.7303k' '+0.00566+0.1807i+0.9579j+0.2231k']

Quaternion Array (2,): 
['+0.1826+0.5477i+0.3651j+0.7303k' '+0.00566+0.1807i+0.9579j+0.2231k']

Quaternion Array (6, 2): 
[['+0-0.926i-0.5387j-0.8014k' '+0-0.5251i-0.5006j-0.5319k'
  '+0-0.5134i-0.9545j-0.7415k' '+0-0.124i-0.6525j-0.07362k'
  '+0-0.8414i-0.9122j-0.8761k' '+0-0.8994i-0.6129j-0.6906k']
 ['+0-0.9119i-0.9875j-0.4615k' '+0-0.9995i-0.5248j-0.09973k'
  '+0-0.8965i-0.09812j-0.4974k' '+0-0.2132i-0.8037j-0.4552k'
  '+0-0.6802i-0.387j-0.2502k' '+0-0.9618i-0.0551j-0.9914k']]

(2, 6)

### Q_num methods

In [134]:
display(qn.stack(qn1,qn2,axis = 1)) # stack in the same way as np.stack
display(qn.qdot(qn1,qn2)) # dot product
display(qn.qcross(qn1,qn2)) # cross product
display(qn.anglebtw(qn1.imag(),qn2.imag())) # if use quaternion number to represent 3d vec, this will give you the angle between two 3d vector
display(qn.reflect(qn1.imag(),qn2.imag())) # first input: normal line of a surface, second input: a 3d vector in quaternion form; this will return the reflected vector
display(qn.rotate(qn1,qn2,np.pi/2))  # first input is the rotation axis, 2nd: point to be rotated, 3rd: rotation angle (optional, if none, directly use qn1 for rotation)

Quaternion Array (2, 2): 
[['+2+7i+6j+11k' '+1+3i+2j+4k']
 ['+0.26+9.3i+46j+13.25k' '+0.13+4.15i+22j+5.123k']]

array([  -75.        , -1118.42334755])

Quaternion Array (2,): 
['+0+15i+15j+15k' '+0-53.47i+19.03j+16.75k']

array([3.05469253, 3.08989077])

Quaternion Array (2,): 
['-1.11e-16-2.233i-2.485j-4.223k' '-1.665e-16-4.598i-21.27j-7.337k']

Quaternion Array (2,): 
['+1.242+3.43i+3.214j+4.759k' '+0.1311+3.258i+21.97j+6.566k']

### Some visualization

In [35]:
from mpl_toolkits.mplot3d import Axes3D
spherePoints = qn.qn(np.random.rand(240,3)-np.array([.5,.5,0])).normalize()
rotateQn     = qn.qn([np.cos(np.pi/2),np.sin(np.pi/2),0,0])
rotatedPoints = rotateQn*spherePoints*rotateQn.conj()
fig = plt.figure()
ax = Axes3D(fig);
ax.scatter(spherePoints.x,spherePoints.y,spherePoints.z,color = 'k')
ax.scatter(rotatedPoints.x,rotatedPoints.y,rotatedPoints.z,color = 'r')
ax.axis('auto');
ax.autoscale = False;